// Curated Tabler icon allowlist for prompt suggestion groups and items.
// Swap from Lucide to Tabler in v1.2 — Tabler's ~6k icon catalog has
// much deeper sports coverage (American Football, Baseball, Basketball,
// Soccer, Tennis, Volleyball, Bowling, Golf, Hockey, Karate, Ski…)
// which Lucide lacks. Same line-weight aesthetic, drop-in component API.
//
// Names stored in the DB are the Tabler export name WITHOUT the "Icon"
// prefix ("BallFootball", not "IconBallFootball") — shorter strings,
// avoids the prefix-stutter, and the runtime map below re-joins the
// prefix when resolving. Server-side validation (parseIconName in
// admin/prompts/actions.ts) uses Object.hasOwn against this map so a
// malicious "toString" or "constructor" value can't sneak through.
//
// Icons are grouped into categories for the admin picker UI. Categories
// are render-only — only the icon name is persisted. Adding an icon:
// (1) import it below, (2) add it to the appropriate category, (3) the
// picker + render both see it automatically, (4) redeploy.

import {
  // Sports
  IconBallAmericanFootball,
  IconBallBaseball,
  IconBallBasketball,
  IconBallFootball,
  IconBallTennis,
  IconBallVolleyball,
  IconBallBowling,
  IconGolf,
  IconDiscGolf,
  IconBat,
  IconHelmet,
  IconKarate,
  IconJetski,
  IconPlayBasketball,
  IconPlayFootball,
  IconRun,
  IconSwimming,
  IconSkiJumping,
  IconIceSkating,
  IconRollerSkating,
  IconYoga,
  IconBike,
  IconMotorbike,
  IconTrekking,
  IconSailboat,
  IconFishHook,
  IconStretching,
  IconBarbell,
  IconBuildingStadium,
  IconTrophy,
  IconMedal,
  IconMedal2,
  IconCup,
  IconAward,
  IconScoreboard,
  // Writing
  IconPencil,
  IconWriting,
  IconEdit,
  IconFeather,
  IconSignature,
  IconTypography,
  IconQuote,
  IconBook,
  IconBook2,
  IconBookmark,
  IconNotes,
  IconNotebook,
  IconMarkdown,
  IconFileText,
  IconClipboardText,
  // Reactions
  IconFlame,
  IconBolt,
  IconSparkles,
  IconStar,
  IconHeart,
  IconMoodHappy,
  IconMoodSad,
  IconMoodCrazyHappy,
  IconMoodWink,
  IconMoodAngry,
  IconMoodKid,
  IconMoodSmile,
  IconGhost,
  IconSkull,
  IconTornado,
  IconConfetti,
  IconPoo,
  IconMasksTheater,
  // Fantasy / roast
  IconSword,
  IconSwords,
  IconShield,
  IconShieldCheck,
  IconCrown,
  IconWand,
  IconDiamond,
  IconDiamonds,
  IconHammer,
  IconAnchor,
  IconRocket,
  IconBomb,
  IconHorseshoe,
  IconDice,
  IconDice1,
  IconDice3,
  IconDice5,
  IconDice6,
  IconChessKing,
  IconChessQueen,
  // Analysis
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconTrendingUp,
  IconTrendingDown,
  IconActivity,
  IconTarget,
  IconTargetArrow,
  IconCrosshair,
  IconMath,
  IconPercentage,
  IconCalculator,
  IconReportAnalytics,
  IconSpy,
  // Media / broadcast
  IconMicrophone,
  IconMicrophone2,
  IconHeadphones,
  IconMusic,
  IconPlayerPlay,
  IconVideo,
  IconMovie,
  IconBroadcast,
  IconDeviceTv,
  IconRadio,
  IconNews,
  IconMessageCircle,
  IconSend,
  IconMail,
  IconPhone,
  IconBell,
  IconBellRinging,
  // Misc / everyday
  IconBeer,
  IconGlassFull,
  IconPizza,
  IconBurger,
  IconCoffee,
  IconCar,
  IconPlane,
  IconMountain,
  IconSunset,
  IconMoon,
  IconSun,
  IconBulb,
  IconGift,
  IconCake,
  IconPaw,
  IconDevices,
  type Icon as TablerIcon,
} from "@tabler/icons-react";

export type PromptIconCategory =
  | "Sports"
  | "Writing"
  | "Reactions"
  | "Fantasy"
  | "Analysis"
  | "Media"
  | "Misc";

/** Display order for the category chips in the admin picker. */
export const PROMPT_ICON_CATEGORIES: readonly PromptIconCategory[] = [
  "Sports",
  "Writing",
  "Reactions",
  "Fantasy",
  "Analysis",
  "Media",
  "Misc",
];

// Name → component map. Keys are Tabler export names WITHOUT the `Icon`
// prefix. Adding a new icon: import above, add here, add to one of the
// category arrays below, done.
export const PROMPT_ICONS: Record<string, TablerIcon> = {
  // Sports
  BallAmericanFootball: IconBallAmericanFootball,
  BallBaseball: IconBallBaseball,
  BallBasketball: IconBallBasketball,
  BallFootball: IconBallFootball,
  BallTennis: IconBallTennis,
  BallVolleyball: IconBallVolleyball,
  BallBowling: IconBallBowling,
  Golf: IconGolf,
  DiscGolf: IconDiscGolf,
  Bat: IconBat,
  Helmet: IconHelmet,
  Karate: IconKarate,
  Jetski: IconJetski,
  PlayBasketball: IconPlayBasketball,
  PlayFootball: IconPlayFootball,
  Run: IconRun,
  Swimming: IconSwimming,
  SkiJumping: IconSkiJumping,
  IceSkating: IconIceSkating,
  RollerSkating: IconRollerSkating,
  Yoga: IconYoga,
  Bike: IconBike,
  Motorbike: IconMotorbike,
  Trekking: IconTrekking,
  Sailboat: IconSailboat,
  FishHook: IconFishHook,
  Stretching: IconStretching,
  Barbell: IconBarbell,
  BuildingStadium: IconBuildingStadium,
  Trophy: IconTrophy,
  Medal: IconMedal,
  Medal2: IconMedal2,
  Cup: IconCup,
  Award: IconAward,
  Scoreboard: IconScoreboard,
  // Writing
  Pencil: IconPencil,
  Writing: IconWriting,
  Edit: IconEdit,
  Feather: IconFeather,
  Signature: IconSignature,
  Typography: IconTypography,
  Quote: IconQuote,
  Book: IconBook,
  Book2: IconBook2,
  Bookmark: IconBookmark,
  Notes: IconNotes,
  Notebook: IconNotebook,
  Markdown: IconMarkdown,
  FileText: IconFileText,
  ClipboardText: IconClipboardText,
  // Reactions
  Flame: IconFlame,
  Bolt: IconBolt,
  Sparkles: IconSparkles,
  Star: IconStar,
  Heart: IconHeart,
  MoodHappy: IconMoodHappy,
  MoodSad: IconMoodSad,
  MoodCrazyHappy: IconMoodCrazyHappy,
  MoodWink: IconMoodWink,
  MoodAngry: IconMoodAngry,
  MoodKid: IconMoodKid,
  MoodSmile: IconMoodSmile,
  Ghost: IconGhost,
  Skull: IconSkull,
  Tornado: IconTornado,
  Confetti: IconConfetti,
  Poo: IconPoo,
  MasksTheater: IconMasksTheater,
  // Fantasy / roast
  Sword: IconSword,
  Swords: IconSwords,
  Shield: IconShield,
  ShieldCheck: IconShieldCheck,
  Crown: IconCrown,
  Wand: IconWand,
  Diamond: IconDiamond,
  Diamonds: IconDiamonds,
  Hammer: IconHammer,
  Anchor: IconAnchor,
  Rocket: IconRocket,
  Bomb: IconBomb,
  Horseshoe: IconHorseshoe,
  Dice: IconDice,
  Dice1: IconDice1,
  Dice3: IconDice3,
  Dice5: IconDice5,
  Dice6: IconDice6,
  ChessKing: IconChessKing,
  ChessQueen: IconChessQueen,
  // Analysis
  ChartBar: IconChartBar,
  ChartLine: IconChartLine,
  ChartPie: IconChartPie,
  TrendingUp: IconTrendingUp,
  TrendingDown: IconTrendingDown,
  Activity: IconActivity,
  Target: IconTarget,
  TargetArrow: IconTargetArrow,
  Crosshair: IconCrosshair,
  Math: IconMath,
  Percentage: IconPercentage,
  Calculator: IconCalculator,
  ReportAnalytics: IconReportAnalytics,
  Spy: IconSpy,
  // Media
  Microphone: IconMicrophone,
  Microphone2: IconMicrophone2,
  Headphones: IconHeadphones,
  Music: IconMusic,
  PlayerPlay: IconPlayerPlay,
  Video: IconVideo,
  Movie: IconMovie,
  Broadcast: IconBroadcast,
  DeviceTv: IconDeviceTv,
  Radio: IconRadio,
  News: IconNews,
  MessageCircle: IconMessageCircle,
  Send: IconSend,
  Mail: IconMail,
  Phone: IconPhone,
  Bell: IconBell,
  BellRinging: IconBellRinging,
  // Misc
  Beer: IconBeer,
  GlassFull: IconGlassFull,
  Pizza: IconPizza,
  Burger: IconBurger,
  Coffee: IconCoffee,
  Car: IconCar,
  Plane: IconPlane,
  Mountain: IconMountain,
  Sunset: IconSunset,
  Moon: IconMoon,
  Sun: IconSun,
  Bulb: IconBulb,
  Gift: IconGift,
  Cake: IconCake,
  Paw: IconPaw,
  Devices: IconDevices,
};

export type PromptIconName = keyof typeof PROMPT_ICONS;

/** Membership by category. The same name must appear under exactly one
 * category (not enforced at compile time — keep this list in sync with
 * the imports above). Used to render the category chips + grid in the
 * admin picker. */
export const PROMPT_ICONS_BY_CATEGORY: Record<
  PromptIconCategory,
  readonly PromptIconName[]
> = {
  Sports: [
    "BallAmericanFootball",
    "BallBaseball",
    "BallBasketball",
    "BallFootball",
    "BallTennis",
    "BallVolleyball",
    "BallBowling",
    "Golf",
    "DiscGolf",
    "Bat",
    "Helmet",
    "Karate",
    "Jetski",
    "PlayBasketball",
    "PlayFootball",
    "Run",
    "Swimming",
    "SkiJumping",
    "IceSkating",
    "RollerSkating",
    "Yoga",
    "Bike",
    "Motorbike",
    "Trekking",
    "Sailboat",
    "FishHook",
    "Stretching",
    "Barbell",
    "BuildingStadium",
    "Trophy",
    "Medal",
    "Medal2",
    "Cup",
    "Award",
    "Scoreboard",
  ],
  Writing: [
    "Pencil",
    "Writing",
    "Edit",
    "Feather",
    "Signature",
    "Typography",
    "Quote",
    "Book",
    "Book2",
    "Bookmark",
    "Notes",
    "Notebook",
    "Markdown",
    "FileText",
    "ClipboardText",
  ],
  Reactions: [
    "Flame",
    "Bolt",
    "Sparkles",
    "Star",
    "Heart",
    "MoodHappy",
    "MoodSad",
    "MoodCrazyHappy",
    "MoodWink",
    "MoodAngry",
    "MoodKid",
    "MoodSmile",
    "Ghost",
    "Skull",
    "Tornado",
    "Confetti",
    "Poo",
    "MasksTheater",
  ],
  Fantasy: [
    "Sword",
    "Swords",
    "Shield",
    "ShieldCheck",
    "Crown",
    "Wand",
    "Diamond",
    "Diamonds",
    "Hammer",
    "Anchor",
    "Rocket",
    "Bomb",
    "Horseshoe",
    "Dice",
    "Dice1",
    "Dice3",
    "Dice5",
    "Dice6",
    "ChessKing",
    "ChessQueen",
  ],
  Analysis: [
    "ChartBar",
    "ChartLine",
    "ChartPie",
    "TrendingUp",
    "TrendingDown",
    "Activity",
    "Target",
    "TargetArrow",
    "Crosshair",
    "Math",
    "Percentage",
    "Calculator",
    "ReportAnalytics",
    "Spy",
  ],
  Media: [
    "Microphone",
    "Microphone2",
    "Headphones",
    "Music",
    "PlayerPlay",
    "Video",
    "Movie",
    "Broadcast",
    "DeviceTv",
    "Radio",
    "News",
    "MessageCircle",
    "Send",
    "Mail",
    "Phone",
    "Bell",
    "BellRinging",
  ],
  Misc: [
    "Beer",
    "GlassFull",
    "Pizza",
    "Burger",
    "Coffee",
    "Car",
    "Plane",
    "Mountain",
    "Sunset",
    "Moon",
    "Sun",
    "Bulb",
    "Gift",
    "Cake",
    "Paw",
    "Devices",
  ],
};

/** All icon names flattened, category order preserved. */
export const PROMPT_ICON_NAMES: readonly PromptIconName[] =
  PROMPT_ICON_CATEGORIES.flatMap((c) => PROMPT_ICONS_BY_CATEGORY[c]);

/** Narrows a raw icon name (from DB or form) into a renderable Tabler
 * component, or null if unknown. Never throws. Uses `Object.hasOwn` to
 * dodge prototype-chain hits like "toString" that would otherwise
 * resolve to a non-component function. */
export function getPromptIcon(name: string | null): TablerIcon | null {
  if (!name) return null;
  if (!Object.hasOwn(PROMPT_ICONS, name)) return null;
  return PROMPT_ICONS[name];
}
