// Curated Tabler icon allowlist for prompt suggestion groups and items.
// Swap from Lucide to Tabler in v1.2 — Tabler's ~6k icon catalog has
// much deeper sports coverage (American Football, Baseball, Basketball,
// Soccer, Tennis, Volleyball, Bowling, Golf, Hockey, Karate, Ski…)
// which Lucide lacks. Same line-weight aesthetic, drop-in component API.
//
// v1.3 (Apr 18) — broadened to ~185 icons across 10 categories with
// richer Food, Travel, and People sets (latter includes explicit
// women-coded icons: Woman, Flower, Perfume, GenderFemale, etc.).
//
// Names stored in the DB are the Tabler export name WITHOUT the "Icon"
// prefix ("BallFootball", not "IconBallFootball") — shorter strings,
// avoids the prefix-stutter. Server-side validation (parseIconName in
// admin/memory/prompts/actions.ts) uses Object.hasOwn against this map so a
// malicious "toString" or "constructor" value can't sneak through.
//
// Icons are grouped into categories for the admin picker UI. Categories
// are render-only — only the icon name is persisted. Adding an icon:
// (1) import it below, (2) add it to PROMPT_ICONS, (3) add to the
// right category array, (4) redeploy.

import {
  // Sports
  IconBallAmericanFootball,
  IconBallBaseball,
  IconBallBasketball,
  IconBallFootball,
  IconBallTennis,
  IconBallVolleyball,
  IconBallBowling,
  IconGolf,
  IconDiscGolf,
  IconBat,
  IconHelmet,
  IconKarate,
  IconJetski,
  IconPlayBasketball,
  IconPlayFootball,
  IconRun,
  IconSwimming,
  IconSkiJumping,
  IconIceSkating,
  IconRollerSkating,
  IconYoga,
  IconBike,
  IconMotorbike,
  IconTrekking,
  IconSailboat,
  IconFishHook,
  IconStretching,
  IconBarbell,
  IconBuildingStadium,
  IconTrophy,
  IconMedal,
  IconMedal2,
  IconCup,
  IconAward,
  IconScoreboard,
  // Writing
  IconPencil,
  IconWriting,
  IconEdit,
  IconFeather,
  IconSignature,
  IconTypography,
  IconQuote,
  IconBook,
  IconBook2,
  IconBookmark,
  IconNotes,
  IconNotebook,
  IconMarkdown,
  IconFileText,
  IconClipboardText,
  // Reactions
  IconFlame,
  IconBolt,
  IconSparkles,
  IconStar,
  IconHeart,
  IconMoodHappy,
  IconMoodSad,
  IconMoodCrazyHappy,
  IconMoodWink,
  IconMoodAngry,
  IconMoodKid,
  IconMoodSmile,
  IconGhost,
  IconSkull,
  IconTornado,
  IconConfetti,
  IconPoo,
  IconMasksTheater,
  // Fantasy / roast
  IconSword,
  IconSwords,
  IconShield,
  IconShieldCheck,
  IconCrown,
  IconWand,
  IconDiamond,
  IconDiamonds,
  IconHammer,
  IconAnchor,
  IconRocket,
  IconBomb,
  IconHorseshoe,
  IconDice,
  IconDice1,
  IconDice3,
  IconDice5,
  IconDice6,
  IconChessKing,
  IconChessQueen,
  // Analysis
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconTrendingUp,
  IconTrendingDown,
  IconActivity,
  IconTarget,
  IconTargetArrow,
  IconCrosshair,
  IconMath,
  IconPercentage,
  IconCalculator,
  IconReportAnalytics,
  IconSpy,
  // Media / broadcast
  IconMicrophone,
  IconMicrophone2,
  IconHeadphones,
  IconMusic,
  IconPlayerPlay,
  IconVideo,
  IconMovie,
  IconBroadcast,
  IconDeviceTv,
  IconRadio,
  IconNews,
  IconMessageCircle,
  IconSend,
  IconMail,
  IconPhone,
  IconBell,
  IconBellRinging,
  // Food
  IconBeer,
  IconGlassFull,
  IconGlassChampagne,
  IconBottle,
  IconBubbleTea,
  IconCoffee,
  IconPizza,
  IconBurger,
  IconCake,
  IconCakeRoll,
  IconCandy,
  IconLollipop,
  IconCookie,
  IconIceCream,
  IconApple,
  IconAvocado,
  IconBread,
  IconCarrot,
  IconCheese,
  IconEgg,
  IconEggFried,
  IconMeat,
  IconSalad,
  IconSoup,
  IconPepper,
  IconBowlChopsticks,
  IconGrill,
  IconGrillFork,
  // Travel
  IconPlane,
  IconCar,
  IconBus,
  IconTrain,
  IconHelicopter,
  IconShip,
  IconAirBalloon,
  IconAmbulance,
  IconLuggage,
  IconBackpack,
  IconTicket,
  IconEPassport,
  IconCompass,
  IconWorld,
  IconMap,
  IconMapPin,
  IconMapPin2,
  IconRoute,
  IconParking,
  IconGasStation,
  IconCamera,
  IconCameraSelfie,
  IconUmbrella,
  IconMountain,
  IconSunset,
  IconBeach,
  IconTent,
  IconCampfire,
  IconBuildingLighthouse,
  IconBuildingCastle,
  IconBuildingBurjAlArab,
  // People (includes women-coded options)
  IconWoman,
  IconMan,
  IconUser,
  IconUsers,
  IconUserHeart,
  IconUserStar,
  IconFriends,
  IconMessageUser,
  IconBabyCarriage,
  IconChefHat,
  IconChalkboardTeacher,
  IconFlower,
  IconPerfume,
  IconGenderFemale,
  IconGenderFemme,
  IconMoodNerd,
  IconMoodBoy,
  IconCookieMan,
  IconTie,
  // Misc
  IconSun,
  IconMoon,
  IconBulb,
  IconGift,
  IconPaw,
  IconDevices,
  type Icon as TablerIcon,
} from "@tabler/icons-react";

export type PromptIconCategory =
  | "Sports"
  | "Writing"
  | "Reactions"
  | "Fantasy"
  | "Analysis"
  | "Media"
  | "Food"
  | "Travel"
  | "People"
  | "Misc";

/** Display order for the category chips in the admin picker. */
export const PROMPT_ICON_CATEGORIES: readonly PromptIconCategory[] = [
  "Sports",
  "People",
  "Food",
  "Travel",
  "Writing",
  "Reactions",
  "Fantasy",
  "Analysis",
  "Media",
  "Misc",
];

// Name → component map. Keys are Tabler export names WITHOUT the `Icon`
// prefix. Adding a new icon: import above, add here, add to one of the
// category arrays below, done.
export const PROMPT_ICONS: Record<string, TablerIcon> = {
  // Sports
  BallAmericanFootball: IconBallAmericanFootball,
  BallBaseball: IconBallBaseball,
  BallBasketball: IconBallBasketball,
  BallFootball: IconBallFootball,
  BallTennis: IconBallTennis,
  BallVolleyball: IconBallVolleyball,
  BallBowling: IconBallBowling,
  Golf: IconGolf,
  DiscGolf: IconDiscGolf,
  Bat: IconBat,
  Helmet: IconHelmet,
  Karate: IconKarate,
  Jetski: IconJetski,
  PlayBasketball: IconPlayBasketball,
  PlayFootball: IconPlayFootball,
  Run: IconRun,
  Swimming: IconSwimming,
  SkiJumping: IconSkiJumping,
  IceSkating: IconIceSkating,
  RollerSkating: IconRollerSkating,
  Yoga: IconYoga,
  Bike: IconBike,
  Motorbike: IconMotorbike,
  Trekking: IconTrekking,
  Sailboat: IconSailboat,
  FishHook: IconFishHook,
  Stretching: IconStretching,
  Barbell: IconBarbell,
  BuildingStadium: IconBuildingStadium,
  Trophy: IconTrophy,
  Medal: IconMedal,
  Medal2: IconMedal2,
  Cup: IconCup,
  Award: IconAward,
  Scoreboard: IconScoreboard,
  // Writing
  Pencil: IconPencil,
  Writing: IconWriting,
  Edit: IconEdit,
  Feather: IconFeather,
  Signature: IconSignature,
  Typography: IconTypography,
  Quote: IconQuote,
  Book: IconBook,
  Book2: IconBook2,
  Bookmark: IconBookmark,
  Notes: IconNotes,
  Notebook: IconNotebook,
  Markdown: IconMarkdown,
  FileText: IconFileText,
  ClipboardText: IconClipboardText,
  // Reactions
  Flame: IconFlame,
  Bolt: IconBolt,
  Sparkles: IconSparkles,
  Star: IconStar,
  Heart: IconHeart,
  MoodHappy: IconMoodHappy,
  MoodSad: IconMoodSad,
  MoodCrazyHappy: IconMoodCrazyHappy,
  MoodWink: IconMoodWink,
  MoodAngry: IconMoodAngry,
  MoodKid: IconMoodKid,
  MoodSmile: IconMoodSmile,
  Ghost: IconGhost,
  Skull: IconSkull,
  Tornado: IconTornado,
  Confetti: IconConfetti,
  Poo: IconPoo,
  MasksTheater: IconMasksTheater,
  // Fantasy / roast
  Sword: IconSword,
  Swords: IconSwords,
  Shield: IconShield,
  ShieldCheck: IconShieldCheck,
  Crown: IconCrown,
  Wand: IconWand,
  Diamond: IconDiamond,
  Diamonds: IconDiamonds,
  Hammer: IconHammer,
  Anchor: IconAnchor,
  Rocket: IconRocket,
  Bomb: IconBomb,
  Horseshoe: IconHorseshoe,
  Dice: IconDice,
  Dice1: IconDice1,
  Dice3: IconDice3,
  Dice5: IconDice5,
  Dice6: IconDice6,
  ChessKing: IconChessKing,
  ChessQueen: IconChessQueen,
  // Analysis
  ChartBar: IconChartBar,
  ChartLine: IconChartLine,
  ChartPie: IconChartPie,
  TrendingUp: IconTrendingUp,
  TrendingDown: IconTrendingDown,
  Activity: IconActivity,
  Target: IconTarget,
  TargetArrow: IconTargetArrow,
  Crosshair: IconCrosshair,
  Math: IconMath,
  Percentage: IconPercentage,
  Calculator: IconCalculator,
  ReportAnalytics: IconReportAnalytics,
  Spy: IconSpy,
  // Media
  Microphone: IconMicrophone,
  Microphone2: IconMicrophone2,
  Headphones: IconHeadphones,
  Music: IconMusic,
  PlayerPlay: IconPlayerPlay,
  Video: IconVideo,
  Movie: IconMovie,
  Broadcast: IconBroadcast,
  DeviceTv: IconDeviceTv,
  Radio: IconRadio,
  News: IconNews,
  MessageCircle: IconMessageCircle,
  Send: IconSend,
  Mail: IconMail,
  Phone: IconPhone,
  Bell: IconBell,
  BellRinging: IconBellRinging,
  // Food
  Beer: IconBeer,
  GlassFull: IconGlassFull,
  GlassChampagne: IconGlassChampagne,
  Bottle: IconBottle,
  BubbleTea: IconBubbleTea,
  Coffee: IconCoffee,
  Pizza: IconPizza,
  Burger: IconBurger,
  Cake: IconCake,
  CakeRoll: IconCakeRoll,
  Candy: IconCandy,
  Lollipop: IconLollipop,
  Cookie: IconCookie,
  IceCream: IconIceCream,
  Apple: IconApple,
  Avocado: IconAvocado,
  Bread: IconBread,
  Carrot: IconCarrot,
  Cheese: IconCheese,
  Egg: IconEgg,
  EggFried: IconEggFried,
  Meat: IconMeat,
  Salad: IconSalad,
  Soup: IconSoup,
  Pepper: IconPepper,
  BowlChopsticks: IconBowlChopsticks,
  Grill: IconGrill,
  GrillFork: IconGrillFork,
  // Travel
  Plane: IconPlane,
  Car: IconCar,
  Bus: IconBus,
  Train: IconTrain,
  Helicopter: IconHelicopter,
  Ship: IconShip,
  AirBalloon: IconAirBalloon,
  Ambulance: IconAmbulance,
  Luggage: IconLuggage,
  Backpack: IconBackpack,
  Ticket: IconTicket,
  Passport: IconEPassport, // Tabler exports it as IconEPassport; DB stores "Passport"
  Compass: IconCompass,
  World: IconWorld,
  Map: IconMap,
  MapPin: IconMapPin,
  MapPin2: IconMapPin2,
  Route: IconRoute,
  Parking: IconParking,
  GasStation: IconGasStation,
  Camera: IconCamera,
  CameraSelfie: IconCameraSelfie,
  Umbrella: IconUmbrella,
  Mountain: IconMountain,
  Sunset: IconSunset,
  Beach: IconBeach,
  Tent: IconTent,
  Campfire: IconCampfire,
  BuildingLighthouse: IconBuildingLighthouse,
  BuildingCastle: IconBuildingCastle,
  BuildingBurjAlArab: IconBuildingBurjAlArab,
  // People
  Woman: IconWoman,
  Man: IconMan,
  User: IconUser,
  Users: IconUsers,
  UserHeart: IconUserHeart,
  UserStar: IconUserStar,
  Friends: IconFriends,
  MessageUser: IconMessageUser,
  BabyCarriage: IconBabyCarriage,
  ChefHat: IconChefHat,
  ChalkboardTeacher: IconChalkboardTeacher,
  Flower: IconFlower,
  Perfume: IconPerfume,
  GenderFemale: IconGenderFemale,
  GenderFemme: IconGenderFemme,
  MoodNerd: IconMoodNerd,
  MoodBoy: IconMoodBoy,
  CookieMan: IconCookieMan,
  Tie: IconTie,
  // Misc
  Sun: IconSun,
  Moon: IconMoon,
  Bulb: IconBulb,
  Gift: IconGift,
  Paw: IconPaw,
  Devices: IconDevices,
};

export type PromptIconName = keyof typeof PROMPT_ICONS;

/** Membership by category. Same name appears under exactly one
 * category. Used to render the category chips + grid in the admin
 * picker. */
export const PROMPT_ICONS_BY_CATEGORY: Record<
  PromptIconCategory,
  readonly PromptIconName[]
> = {
  Sports: [
    "BallAmericanFootball",
    "BallBaseball",
    "BallBasketball",
    "BallFootball",
    "BallTennis",
    "BallVolleyball",
    "BallBowling",
    "Golf",
    "DiscGolf",
    "Bat",
    "Helmet",
    "Karate",
    "Jetski",
    "PlayBasketball",
    "PlayFootball",
    "Run",
    "Swimming",
    "SkiJumping",
    "IceSkating",
    "RollerSkating",
    "Yoga",
    "Bike",
    "Motorbike",
    "Trekking",
    "Sailboat",
    "FishHook",
    "Stretching",
    "Barbell",
    "BuildingStadium",
    "Trophy",
    "Medal",
    "Medal2",
    "Cup",
    "Award",
    "Scoreboard",
  ],
  People: [
    "Woman",
    "Man",
    "User",
    "Users",
    "UserHeart",
    "UserStar",
    "Friends",
    "MessageUser",
    "BabyCarriage",
    "ChefHat",
    "ChalkboardTeacher",
    "Flower",
    "Perfume",
    "GenderFemale",
    "GenderFemme",
    "MoodNerd",
    "MoodBoy",
    "CookieMan",
    "Tie",
  ],
  Food: [
    "Beer",
    "GlassFull",
    "GlassChampagne",
    "Bottle",
    "BubbleTea",
    "Coffee",
    "Pizza",
    "Burger",
    "Cake",
    "CakeRoll",
    "Candy",
    "Lollipop",
    "Cookie",
    "IceCream",
    "Apple",
    "Avocado",
    "Bread",
    "Carrot",
    "Cheese",
    "Egg",
    "EggFried",
    "Meat",
    "Salad",
    "Soup",
    "Pepper",
    "BowlChopsticks",
    "Grill",
    "GrillFork",
  ],
  Travel: [
    "Plane",
    "Car",
    "Bus",
    "Train",
    "Helicopter",
    "Ship",
    "AirBalloon",
    "Ambulance",
    "Luggage",
    "Backpack",
    "Ticket",
    "Passport",
    "Compass",
    "World",
    "Map",
    "MapPin",
    "MapPin2",
    "Route",
    "Parking",
    "GasStation",
    "Camera",
    "CameraSelfie",
    "Umbrella",
    "Mountain",
    "Sunset",
    "Beach",
    "Tent",
    "Campfire",
    "BuildingLighthouse",
    "BuildingCastle",
    "BuildingBurjAlArab",
  ],
  Writing: [
    "Pencil",
    "Writing",
    "Edit",
    "Feather",
    "Signature",
    "Typography",
    "Quote",
    "Book",
    "Book2",
    "Bookmark",
    "Notes",
    "Notebook",
    "Markdown",
    "FileText",
    "ClipboardText",
  ],
  Reactions: [
    "Flame",
    "Bolt",
    "Sparkles",
    "Star",
    "Heart",
    "MoodHappy",
    "MoodSad",
    "MoodCrazyHappy",
    "MoodWink",
    "MoodAngry",
    "MoodKid",
    "MoodSmile",
    "Ghost",
    "Skull",
    "Tornado",
    "Confetti",
    "Poo",
    "MasksTheater",
  ],
  Fantasy: [
    "Sword",
    "Swords",
    "Shield",
    "ShieldCheck",
    "Crown",
    "Wand",
    "Diamond",
    "Diamonds",
    "Hammer",
    "Anchor",
    "Rocket",
    "Bomb",
    "Horseshoe",
    "Dice",
    "Dice1",
    "Dice3",
    "Dice5",
    "Dice6",
    "ChessKing",
    "ChessQueen",
  ],
  Analysis: [
    "ChartBar",
    "ChartLine",
    "ChartPie",
    "TrendingUp",
    "TrendingDown",
    "Activity",
    "Target",
    "TargetArrow",
    "Crosshair",
    "Math",
    "Percentage",
    "Calculator",
    "ReportAnalytics",
    "Spy",
  ],
  Media: [
    "Microphone",
    "Microphone2",
    "Headphones",
    "Music",
    "PlayerPlay",
    "Video",
    "Movie",
    "Broadcast",
    "DeviceTv",
    "Radio",
    "News",
    "MessageCircle",
    "Send",
    "Mail",
    "Phone",
    "Bell",
    "BellRinging",
  ],
  Misc: ["Sun", "Moon", "Bulb", "Gift", "Paw", "Devices"],
};

/** All icon names flattened, category order preserved. */
export const PROMPT_ICON_NAMES: readonly PromptIconName[] =
  PROMPT_ICON_CATEGORIES.flatMap((c) => PROMPT_ICONS_BY_CATEGORY[c]);

/** Narrows a raw icon name (from DB or form) into a renderable Tabler
 * component, or null if unknown. Never throws. Uses `Object.hasOwn` to
 * dodge prototype-chain hits like "toString" that would otherwise
 * resolve to a non-component function. */
export function getPromptIcon(name: string | null): TablerIcon | null {
  if (!name) return null;
  if (!Object.hasOwn(PROMPT_ICONS, name)) return null;
  return PROMPT_ICONS[name];
}
